[workspace]
members = [".", "logger"]

[package]
name = "firehose-geyser-plugin"
version = "4.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hashbrown = "0.16"
ahash = "0.8"
rustc-hash = "2.1"
lazy_static = "1.5.0"
tokio = "1.41.0"
bincode = "3.0.0"
log = "0.4.32"
prost-types = "0.14"
prost = "0.14.3"
rbase64 = "2.0.3"
serde_json = "1.0.150"
serde = { version = "1.0.215", features = ["derive"] }
env_logger = "0.11"
gxhash = "3.4.1"
hex = "0.4.3"
bs58 = "0.5"
solana-hash = "4.4.0"
solana-pubkey = "4.1.0"
solana-signature = "3.4.1"

agave-geyser-plugin-interface = "=4.1.0-beta.2"
solana-rpc-client = "=4.1.0-beta.2"
solana-rpc-client-api = "=4.1.0-beta.2"
solana-transaction-status = "=4.1.0-beta.2"
solana-transaction-context = "=4.1.0-beta.2"
solana-commitment-config = "3.1.1"
solana-message = "4.2.0"
solana-program = "=4.0.0" # not upgraded to 4.1.x yet
solana-transaction = "4.1.2"

[dev-dependencies]
tempfile = "3.27.0"
wiremock = "0.6.5"
pretty_assertions = { version = "1.4.1", default-features = false, features = [
    "alloc",
] }
criterion = { version = "0.8", features = ["html_reports"] }
testing_logger = "0.1"

[profile.release]
lto = true
codegen-units = 1

[[bench]]
name = "startup_benchmark"
harness = false

[[bench]]
name = "fixed_length_benchmark"
harness = false
